name: Flujo de trabajo para ejecutar los test
on: [merge_group, push]
jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      GITHUB_LOGIN: ${{ github.actor }}
      GITHUB_PACKAGES: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: |
          chmod +x gradlew
          ./gradlew build -x test --no-daemon
  Test:
    runs-on: ubuntu-latest
    needs: [Build]
    env:
      GITHUB_LOGIN: ${{ github.actor }}
      GITHUB_PACKAGES: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Tests
        run: |
          chmod +x gradlew
          ./gradlew test --no-daemon
  Deploy:
    runs-on: ubuntu-latest
    needs: [Test]
    env:
      GITHUB_LOGIN: ${{ github.actor }}
      GITHUB_PACKAGES: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Deploy
        run: |
          echo "Está añadiendo una nueva versión"
          chmod +x gradlew
          ./gradlew publish
      - name: Send email
        # You may pin to the exact commit or the version.
        # uses: dawidd6/action-send-mail@2cea9617b09d79a095af21254fbcb7ae95903dde
        uses: dawidd6/action-send-mail@v3.12.0
        with:
          # SMTP server address
          server_address: us.es
          subject: "Se ha publicado un nuevo artefacto"
          # Recipients mail addresses (separated with comma)
          to: <irm@us.es>
          # Full name of mail sender (might be with an email address specified in <>)
          from: "juarosalo.us.es"
          # Body of mail message (might be a filename prefixed with file:// to read from)
              
